# Configuración de análisis optimizada para desarrollo fluido
include: package:flutter_lints/flutter.yaml

analyzer:
  # Excluir archivos generados del análisis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "build/**"
    - ".dart_tool/**"

  # Configuración de errores
  errors:
    # Convertir algunos errores en warnings para no interrumpir
    invalid_assignment: warning
    missing_return: warning
    dead_code: info
    unused_import: info
    unused_local_variable: info

  # Configuración de lenguaje
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Reglas básicas habilitadas
    avoid_print: false  # Permitir prints para debugging
    prefer_single_quotes: true
    use_key_in_widget_constructors: false  # No requerir keys siempre

    # Reglas de estilo más relajadas
    lines_longer_than_80_chars: false  # Permitir líneas largas
    avoid_unnecessary_containers: false
    sized_box_for_whitespace: false

    # Reglas de documentación relajadas
    public_member_api_docs: false
    package_api_docs: false

    # Reglas de imports más flexibles
    avoid_relative_lib_imports: false

    # Reglas de performance importantes (mantener)
    avoid_slow_async_io: true
    close_sinks: true

    # Reglas de seguridad importantes (mantener)
    avoid_web_libraries_in_flutter: true

    # Reglas de buenas prácticas pero no críticas
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false

    # Reglas específicas para Flutter
    use_build_context_synchronously: false  # Muy estricta para desarrollo
