// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HgzPllcTIXsj5bYYmfbO2GukWka5tPk',
    appId: '1:363618177033:web:24f1a4c0b627b64c4de8d8',
    messagingSenderId: '363618177033',
    projectId: 'ecf-facturacion',
    authDomain: 'ecf-facturacion.firebaseapp.com',
    storageBucket: 'ecf-facturacion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0zQF-4w5L1EUsetM-vZhAZQkAyPchj9I',
    appId: '1:363618177033:android:375be70e4f7201374de8d8',
    messagingSenderId: '363618177033',
    projectId: 'ecf-facturacion',
    storageBucket: 'ecf-facturacion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvi3tVgu-9P1fDPjGsbTHPnQylh5bdomc',
    appId: '1:363618177033:ios:c307ee5e000c5b7a4de8d8',
    messagingSenderId: '363618177033',
    projectId: 'ecf-facturacion',
    storageBucket: 'ecf-facturacion.firebasestorage.app',
    iosBundleId: 'com.starsoft.ecffacturacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvi3tVgu-9P1fDPjGsbTHPnQylh5bdomc',
    appId: '1:363618177033:ios:c307ee5e000c5b7a4de8d8',
    messagingSenderId: '363618177033',
    projectId: 'ecf-facturacion',
    storageBucket: 'ecf-facturacion.firebasestorage.app',
    iosBundleId: 'com.starsoft.ecffacturacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2HgzPllcTIXsj5bYYmfbO2GukWka5tPk',
    appId: '1:363618177033:web:37e69ca96dbda4494de8d8',
    messagingSenderId: '363618177033',
    projectId: 'ecf-facturacion',
    authDomain: 'ecf-facturacion.firebaseapp.com',
    storageBucket: 'ecf-facturacion.firebasestorage.app',
  );
}
